name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'release还是prerelease'
        required: false
        default: 'release'
        type: choice
        options:
          - 'release'
          - 'prerelease'
  repository_dispatch:
    types: [release, prerelease]

jobs:
  release:
    runs-on: macOS-15
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Resolve release target
        run: |
          set -euo pipefail

          if [[ "${{ github.event_name }}" == "repository_dispatch" && "${{ github.event.action }}" == "prerelease" ]] || [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.release }}" == "prerelease" ]]; then
          #if [ "${{ github.event_name }}" = "repository_dispatch" ] && [ "${{ github.event.action }}" = "prerelease" ]; then
            version_file="version-prerelease"
            prerelease=true
          else
            version_file="version"
            prerelease=false
          fi

          if [ -f "$version_file" ]; then
            tag="$(cat "$version_file")"
          else
            echo "Version file not found: $version_file"
            exit 1
          fi

          tag_no_v="${tag#v}"
          echo "tag=${tag}" >> "$GITHUB_ENV"
          echo "tag_no_v=${tag_no_v}" >> "$GITHUB_ENV"
          echo "update_apple=true" >> "$GITHUB_ENV"
          echo "prerelease=${prerelease}" >> "$GITHUB_ENV"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.25"

      - name: Setup Xcode stable
        run: |
          sudo xcode-select -s /Applications/Xcode.app
          xcodebuild -version >> "$GITHUB_STEP_SUMMARY"

      - name: Install ldid
        run: brew install ldid

      - name: Build TIPA and xcframework
        run: |
          set -euo pipefail
          cd $HOME
          
          echo "sing-box-${{ env.tag }}" >> $GITHUB_STEP_SUMMARY
          git clone -b ${{ env.tag }} --recurse-submodules --depth 1 https://github.com/SagerNet/sing-box.git

          if [ "${{ env.update_apple }}" = "true" ]; then
            rm -rf clients/apple
            git clone --recurse-submodules --depth 1 https://github.com/SagerNet/sing-box-for-apple.git clients/apple
          fi

          export XCODEPROJ_NAME=sing-box
          export APPLICATION_NAME=sing-box
          export SCHEME_NAME=SFI

          cd $HOME/sing-box

          make lib_install
          export PATH="$PATH:$(go env GOPATH)/bin"

          go run ./cmd/internal/build_libbox -target apple -platform ios,tvos,macos
          zip -ry ./Libbox.xcframework.zip ./Libbox.xcframework
          mv Libbox.xcframework clients/apple

          cd clients/apple

          xcodebuild \
            -project sing-box.xcodeproj \
            -scheme SFI \
            -destination "generic/platform=iOS" \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath DerivedData \
            build \
            STRIP_INSTALLED_PRODUCT=NO \
            ARCHS=arm64 \
            ONLY_ACTIVE_ARCH=YES \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            COMPILER_INDEX_STORE_ENABLE=NO \
            SWIFT_SERIALIZE_DEBUGGING_OPTIONS=NO

          app_path="DerivedData/Build/Products/Release-iphoneos/sing-box.app"
          ldid -SSFI/SFI.entitlements "$app_path/sing-box"
          ldid -SExtension/Extension.entitlements "$app_path/PlugIns/Extension.appex/Extension"
          ldid -SIntentsExtension/IntentsExtension.entitlements "$app_path/Extensions/IntentsExtension.appex/IntentsExtension"

          mkdir -p packages/Payload
          cp -rp "$app_path" packages/Payload
          cd packages
          zip -qr sing-box.tipa Payload
          mv sing-box.tipa "${GITHUB_WORKSPACE}/sing-box-${{ env.tag_no_v }}.tipa"
          cd "${GITHUB_WORKSPACE}"
          echo -e "SHA256 Checksum:\n$(shasum -a 256 sing-box-${{ env.tag_no_v }}.tipa)" >> "$GITHUB_STEP_SUMMARY"

      - name: Detect checksum
        shell: bash
        run: |
          checksum=$(shasum -a 256 box/Libbox.xcframework.zip | awk '{print $1}')
          echo "file_checksum=$checksum" >> "$GITHUB_ENV"

      - name: Update Package.swift
        shell: bash
        run: |
          cat > Package.swift << EOF
          // swift-tools-version: 5.7

          import PackageDescription

          let package = Package(
            name: "Libbox",
            platforms: [.iOS(.v12)],
            products: [
              .library(name: "Libbox", targets: ["Libbox"]),
            ],
            targets: [
              .binaryTarget(
                name: "Libbox",
                url: "https://github.com/liujixings/sing-box-lib/releases/download/${{ env.tag }}/Libbox.xcframework.zip",
                checksum: "${{ env.file_checksum }}"
              )
            ]
          )
          EOF

      - name: Commit manifest & tag
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Libbox Release ${{ env.tag }}"
          commit_user_name: "liujixings"
          commit_user_email: "liujixings@outlook.com"
          tagging_message: "${{ env.tag }}"
          file_pattern: Package.swift

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: ${{ env.prerelease == 'true' }}
          tag_name: ${{ env.tag }}
          name: ${{ env.tag_no_v }}
          body: "Compiled from source tag: ${{ env.tag }}"
          files: |
            sing-box/Libbox.xcframework.zip
            sing-box-*.tipa
