name: Update sing-box version

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    permissions:
      contents: write

    steps:
      - name: Get latest sing-box versions
        id: latest
        run: |
          releases_json=$(gh api -X GET "repos/SagerNet/sing-box/releases?per_page=50")
          latest_release=$(echo "$releases_json" | jq -r '.[] | select(.draft == false and .prerelease == false) | .tag_name' | head -n 1)
          latest_prerelease=$(echo "$releases_json" | jq -r '.[] | select(.draft == false and .prerelease == true) | .tag_name' | head -n 1)

          if [ -z "$latest_release" ] || [ -z "$latest_prerelease" ]; then
            echo "Failed to get latest versions"
            exit 1
          fi

          echo "release=${latest_release}" >> "$GITHUB_OUTPUT"
          echo "prerelease=${latest_prerelease}" >> "$GITHUB_OUTPUT"

      - name: Compare repository variables
        id: compare
        run: |
          if [ "${{ vars.RELEASE }}" != "${{ steps.latest.outputs.release }}" ]; then
            echo "release_update_needed=true" >> "$GITHUB_OUTPUT"
          else
            echo "release_update_needed=false" >> "$GITHUB_OUTPUT"
          fi

          if [ "${{ vars.PRERELEASE }}" != "${{ steps.latest.outputs.prerelease }}" ]; then
            echo "prerelease_update_needed=true" >> "$GITHUB_OUTPUT"
          else
            echo "prerelease_update_needed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Update release variable
        if: steps.compare.outputs.release_update_needed == 'true'
        run: |
          gh variable set RELEASE --body "${{ steps.latest.outputs.release }}" --repo "liujixings/sing-box-lib"

      - name: Repository Dispatch (release)
        if: steps.compare.outputs.release_update_needed == 'true'
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: release
          client-payload: '{"version": "${{ steps.latest.outputs.release }}"}'

      - name: Update prerelease variable
        if: steps.compare.outputs.prerelease_update_needed == 'true'
        run: |
          gh variable set PRERELEASE --body "${{ steps.latest.outputs.prerelease }}" --repo "liujixings/sing-box-lib"

      - name: Repository Dispatch (prerelease)
        if: steps.compare.outputs.prerelease_update_needed == 'true'
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: prerelease
          client-payload: '{"version": "${{ steps.latest.outputs.prerelease }}"}'
